packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - electron
  - get-windows
  - uiohook-napi

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
